from httpd:2.4
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY httpd-ssl.conf /usr/local/apache2/conf/httpd-ssl.conf
COPY private.key /usr/local/apache2/conf/ssl/private.key
COPY certificate.crt /usr/local/apache2/conf/ssl/certificate.crt
EXPOSE 443
